import {
  LayoutGrid,
  Briefcase,
  Stethoscope,
  Code2,
  GraduationCap,
} from "lucide-react";

export const ROLE_TEMPLATES: any = {
  sales: {
    id: "sales",
    label: "Sales CRM",
    description: "Track leads, negotiations, and closings.",
    icon: LayoutGrid,
    color: "bg-blue-500",
    stages: [
      { id: "New", title: "New Lead", color: "bg-blue-500" },
      { id: "Contacted", title: "Contacted", color: "bg-indigo-500" },
      { id: "Proposal", title: "Proposal Sent", color: "bg-purple-500" },
      { id: "Negotiation", title: "Negotiation", color: "bg-orange-500" },
      { id: "Won", title: "Won", color: "bg-emerald-500" },
      { id: "Lost", title: "Lost", color: "bg-red-500" },
    ],
  },
  freelancer: {
    id: "freelancer",
    label: "Freelancer",
    description: "Manage clients, projects, and payments.",
    icon: Briefcase,
    color: "bg-emerald-500",
    stages: [
      { id: "Inquiry", title: "Inquiry", color: "bg-slate-500" },
      { id: "Qualified", title: "Qualified", color: "bg-blue-500" },
      { id: "Proposal", title: "Proposal Sent", color: "bg-indigo-500" },
      { id: "Active", title: "In Progress", color: "bg-amber-500" },
      { id: "Review", title: "In Review", color: "bg-purple-500" },
      { id: "Paid", title: "Completed & Paid", color: "bg-emerald-500" },
    ],
  },
  doctor: {
    id: "doctor",
    label: "Doctor / Clinic",
    description: "Track patients, appointments, and treatments.",
    icon: Stethoscope,
    color: "bg-rose-500",
    stages: [
      { id: "New", title: "New Patient", color: "bg-rose-500" },
      { id: "Scheduled", title: "Appt Scheduled", color: "bg-blue-500" },
      { id: "Consultation", title: "In Consultation", color: "bg-indigo-500" },
      { id: "Treatment", title: "Treatment", color: "bg-amber-500" },
      { id: "FollowUp", title: "Follow-up", color: "bg-orange-500" },
      { id: "Discharged", title: "Discharged", color: "bg-emerald-500" },
    ],
  },
  engineer: {
    id: "engineer",
    label: "Engineer / Dev",
    description: "Manage requirements, sprints, and deployment.",
    icon: Code2,
    color: "bg-cyan-500",
    stages: [
      { id: "Requirements", title: "Requirements", color: "bg-slate-500" },
      { id: "Design", title: "Design / Specs", color: "bg-blue-500" },
      { id: "Development", title: "In Development", color: "bg-cyan-500" },
      { id: "Testing", title: "Testing / QA", color: "bg-amber-500" },
      { id: "Deployment", title: "Deployment", color: "bg-indigo-500" },
      { id: "Live", title: "Live / Done", color: "bg-emerald-500" },
    ],
  },
  student: {
    id: "student",
    label: "Student",
    description: "Track internships, job applications, and assignments.",
    icon: GraduationCap,
    color: "bg-violet-500",
    stages: [
      { id: "ToExplore", title: "To Explore", color: "bg-slate-500" },
      { id: "Applied", title: "Applied", color: "bg-blue-500" },
      { id: "Interview", title: "Interviewing", color: "bg-amber-500" },
      { id: "Offer", title: "Offer Received", color: "bg-emerald-500" },
      { id: "Rejected", title: "Rejected", color: "bg-red-500" },
    ],
  },
};
